In [51]:
import torch

### Basics

In [52]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [53]:
x.numel()

12

In [54]:
x.shape

torch.Size([12])

In [55]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [56]:
# elements of vector are laid out one row at a time and thus x[3] == X[0, 3]
x[3] == X[0, 3]

tensor(True)

In [57]:
X.size()

torch.Size([3, 4])

In [58]:
# to automatically infer one component of the shape, we can place a -1 for the shape component that should be inferred automatically
x.reshape(-1, 4)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [59]:
torch.zeros(2, 3, 4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [60]:
torch.ones(2, 3, 4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [61]:
# a tensor with elements drawn from a standard Gaussian (normal) distribution with mean 0 and standard deviation 1
torch.randn(3, 4)

tensor([[-1.3583,  1.1934, -0.0421,  1.4522],
        [ 0.0543,  1.1381, -1.1218, -0.1324],
        [ 1.9614, -0.0423, -1.7887, -0.3765]])

In [62]:
# tensor from Python lists
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

### Indexing and Slicing

In [63]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [64]:
X[-1] # negative (reverse) indexing

tensor([ 8.,  9., 10., 11.])

In [65]:
X[1:3] # slicing - includes the first index (start) but not the last (stop)

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [66]:
X[1, 2] = 17 # write elements of a matrix by specifying indices
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [67]:
X[:2, :] = 12 # : takes all element along selected axis, :<number> takes first <number> elements
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

### Operations

In [68]:
x

tensor([12., 12., 12., 12., 12., 12., 12., 12.,  8.,  9., 10., 11.])

In [69]:
torch.exp(x)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

In [70]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

In [71]:
x + y

tensor([ 3.,  4.,  6., 10.])

In [72]:
x - y

tensor([-1.,  0.,  2.,  6.])

In [73]:
x * y

tensor([ 2.,  4.,  8., 16.])

In [74]:
x / y

tensor([0.5000, 1.0000, 2.0000, 4.0000])

In [75]:
x ** y

tensor([ 1.,  4., 16., 64.])

In [79]:
X = torch.arange(12, dtype=torch.float32). reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [80]:
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
Y

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [81]:
torch.cat((X, Y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [82]:
torch.cat((X, Y), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [83]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [84]:
X.sum()

tensor(66.)