In [65]:
import torch

### Basics

In [66]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [67]:
x.numel()

12

In [68]:
x.shape

torch.Size([12])

In [69]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [70]:
# elements of vector are laid out one row at a time and thus x[3] == X[0, 3]
x[3] == X[0, 3]

tensor(True)

In [71]:
X.size()

torch.Size([3, 4])

In [72]:
# to automatically infer one component of the shape, we can place a -1 for the shape component that should be inferred automatically
x.reshape(-1, 4)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [73]:
torch.zeros(2, 3, 4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [74]:
torch.ones(2, 3, 4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [75]:
# a tensor with elements drawn from a standard Gaussian (normal) distribution with mean 0 and standard deviation 1
torch.randn(3, 4)

tensor([[ 1.3210,  0.1398, -0.1289, -0.6595],
        [-0.6710, -0.2877, -1.3608,  1.8652],
        [ 1.1008,  1.2508,  0.0260, -1.1841]])

In [76]:
# tensor from Python lists
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])